### ISSUE TITLE
Re-license as Unlicenced or similar

### ISSUE THREAD

**Issue by stuzart** [ruby-rdf/rdf-virtuoso#13]
I'd like to re-raise the topic of re-licensing this gem from GPL 3 to Unlicensed. This would bring it in line with the other ruby-rdf libraries, and I also believe would increase its usage. Many rails and ruby applications are licensed as MIT, Apache or BSD-3 & I've sadly had to stop using the gem due to license incompatibilities. This is a shame as it is a nicely written and useful piece of work.

To change the license would require permission from contributors @bensinober , @pkordel , @boutros and @gkellogg 

If there is agreement, I can happily make the necessary changes and prepare the new version ready for release.

**Comment by bensinober** [comment]
I have no thoughts on the matter, other than to let @gkellogg choose license as would best fit the ruby-rdf project

**Comment by gkellogg** [comment]
The organization generally uses the Unlicense, and it would be great to change the license for this repo to [Unlicense](https://unlicense.org). However, as @stuzart says, it requires the permission from the current license holders / original authors who set up the GPL. That would just leave @pkordel and @boutros, I believe. It's a fairly simple change after that, and I'd be happy to put together a PR if there's consensus.

Practically speaking, there's little difference for an open-source project. GPL requires changes to be submitted back, and Unlicense makes no requirements. It's subject to interpretation on how using a GPL licensed gem in another project affects the license of any project using the gem, and Unlicense leaves not ambiguity, which is why I favor it.

Generally, all other repos in this organization use the Unlicense, and given the organization settings, any new contributions to this repo will ask people to agree to the Unlicense terms anyway.
